FROM wazoplatform/asterisk

RUN true \
	&& apt-get update \
	&& apt-get install -y \
		asterisk-sounds-main \
		odbc-postgresql \
		wazo-sounds-en-us \
		wazo-sounds-fr-ca \
		wazo-sounds-fr-fr \
		python3 \
		python3-venv \
		netcat \
	&& python3 -m venv /opt/venv3 \
	&& PATH="/opt/venv3/bin:$PATH" \
	&& pip3 install wheel \
	&& pip3 install https://github.com/wazo-platform/wazo-confgend-client/archive/master.zip \
	&& ln -s /opt/venv3/bin/wazo-confgen /usr/bin/wazo-confgen \
	&& apt-get clean \
	&& pip clear cache

